sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd RestWithDotNet5/RestWithDotNet5/
  - echo "We are in the right folder"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-dot-net-5:dev $DOCKER_USERNAME/rest-with-dot-net-5-db:$TRAVIS_JOB_ID;
    docker tag rest-with-dot-net-5-db:latest $DOCKER_USERNAME/rest-with-dot-net-5-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-dot-net-5:$TRAVIS_JOB_ID
    docker push $DOCKER_USERNAME/rest-with-dot-net-5-db:$TRAVIS_JOB_ID
  on:
    branch: master
notifications:
  email: false
